# Generated by Django 4.2.2 on 2023-06-15 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='send',
            new_name='send_with_post',
        ),
    ]
