# Generated by Django 4.2.2 on 2023-06-15 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_rename_send_delivery_send_with_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='send_price_and_total_price',
            new_name='total_cost',
        ),
    ]
