# Generated by Django 4.2.2 on 2023-06-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_rename_send_price_and_total_price_delivery_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='total_cost',
        ),
    ]
