# Generated by Django 4.2.2 on 2023-06-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_remove_delivery_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
