# Generated by Django 4.2.2 on 2023-06-17 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0004_shopping_cart_order'),
        ('delivery', '0006_alter_delivery_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='shopping_cart',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='shopping_cart.shopping_cart'),
        ),
    ]
