# Generated by Django 4.2.3 on 2023-07-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('#f0f8ff', '#f0f8ff'), ('#faebd7', '#faebd7'), ('#00ffff', '#00ffff'), ('#7fffd4', '#7fffd4'), ('#f0ffff', '#f0ffff'), ('#f5f5dc', '#f5f5dc'), ('#ffe4c4', '#ffe4c4'), ('#000000', '#000000'), ('#ffebcd', '#ffebcd'), ('#0000ff', '#0000ff'), ('#8a2be2', '#8a2be2'), ('#a52a2a', '#a52a2a'), ('#deb887', '#deb887'), ('#5f9ea0', '#5f9ea0'), ('#7fff00', '#7fff00'), ('#d2691e', '#d2691e'), ('#ff7f50', '#ff7f50'), ('#6495ed', '#6495ed'), ('#fff8dc', '#fff8dc'), ('#dc143c', '#dc143c'), ('#00ffff', '#00ffff'), ('#00008b', '#00008b'), ('#008b8b', '#008b8b'), ('#b8860b', '#b8860b'), ('#a9a9a9', '#a9a9a9'), ('#a9a9a9', '#a9a9a9'), ('#006400', '#006400'), ('#bdb76b', '#bdb76b'), ('#8b008b', '#8b008b'), ('#556b2f', '#556b2f'), ('#ff8c00', '#ff8c00'), ('#9932cc', '#9932cc'), ('#8b0000', '#8b0000'), ('#e9967a', '#e9967a'), ('#8fbc8f', '#8fbc8f'), ('#483d8b', '#483d8b'), ('#2f4f4f', '#2f4f4f'), ('#2f4f4f', '#2f4f4f'), ('#00ced1', '#00ced1'), ('#9400d3', '#9400d3'), ('#ff1493', '#ff1493'), ('#00bfff', '#00bfff'), ('#696969', '#696969'), ('#696969', '#696969'), ('#1e90ff', '#1e90ff'), ('#b22222', '#b22222'), ('#fffaf0', '#fffaf0'), ('#228b22', '#228b22'), ('#ff00ff', '#ff00ff'), ('#dcdcdc', '#dcdcdc'), ('#f8f8ff', '#f8f8ff'), ('#ffd700', '#ffd700'), ('#daa520', '#daa520'), ('#808080', '#808080'), ('#808080', '#808080'), ('#008000', '#008000'), ('#adff2f', '#adff2f'), ('#f0fff0', '#f0fff0'), ('#ff69b4', '#ff69b4'), ('#cd5c5c', '#cd5c5c'), ('#4b0082', '#4b0082'), ('#fffff0', '#fffff0'), ('#f0e68c', '#f0e68c'), ('#e6e6fa', '#e6e6fa'), ('#fff0f5', '#fff0f5'), ('#7cfc00', '#7cfc00'), ('#fffacd', '#fffacd'), ('#add8e6', '#add8e6'), ('#f08080', '#f08080'), ('#e0ffff', '#e0ffff'), ('#fafad2', '#fafad2'), ('#d3d3d3', '#d3d3d3'), ('#d3d3d3', '#d3d3d3'), ('#90ee90', '#90ee90'), ('#ffb6c1', '#ffb6c1'), ('#ffa07a', '#ffa07a'), ('#20b2aa', '#20b2aa'), ('#87cefa', '#87cefa'), ('#778899', '#778899'), ('#778899', '#778899'), ('#b0c4de', '#b0c4de'), ('#ffffe0', '#ffffe0'), ('#00ff00', '#00ff00'), ('#32cd32', '#32cd32'), ('#faf0e6', '#faf0e6'), ('#ff00ff', '#ff00ff'), ('#800000', '#800000'), ('#66cdaa', '#66cdaa'), ('#0000cd', '#0000cd'), ('#ba55d3', '#ba55d3'), ('#9370db', '#9370db'), ('#3cb371', '#3cb371'), ('#7b68ee', '#7b68ee'), ('#00fa9a', '#00fa9a'), ('#48d1cc', '#48d1cc'), ('#c71585', '#c71585'), ('#191970', '#191970'), ('#f5fffa', '#f5fffa'), ('#ffe4e1', '#ffe4e1'), ('#ffe4b5', '#ffe4b5'), ('#ffdead', '#ffdead'), ('#000080', '#000080'), ('#fdf5e6', '#fdf5e6'), ('#808000', '#808000'), ('#6b8e23', '#6b8e23'), ('#ffa500', '#ffa500'), ('#ff4500', '#ff4500'), ('#da70d6', '#da70d6'), ('#eee8aa', '#eee8aa'), ('#98fb98', '#98fb98'), ('#afeeee', '#afeeee'), ('#db7093', '#db7093'), ('#ffefd5', '#ffefd5'), ('#ffdab9', '#ffdab9'), ('#cd853f', '#cd853f'), ('#ffc0cb', '#ffc0cb'), ('#dda0dd', '#dda0dd'), ('#b0e0e6', '#b0e0e6'), ('#800080', '#800080'), ('#ff0000', '#ff0000'), ('#bc8f8f', '#bc8f8f'), ('#4169e1', '#4169e1'), ('#8b4513', '#8b4513'), ('#fa8072', '#fa8072'), ('#f4a460', '#f4a460'), ('#2e8b57', '#2e8b57'), ('#fff5ee', '#fff5ee'), ('#a0522d', '#a0522d'), ('#c0c0c0', '#c0c0c0'), ('#87ceeb', '#87ceeb'), ('#6a5acd', '#6a5acd'), ('#708090', '#708090'), ('#708090', '#708090'), ('#fffafa', '#fffafa'), ('#00ff7f', '#00ff7f'), ('#4682b4', '#4682b4'), ('#d2b48c', '#d2b48c'), ('#008080', '#008080'), ('#d8bfd8', '#d8bfd8'), ('#ff6347', '#ff6347'), ('#40e0d0', '#40e0d0'), ('#ee82ee', '#ee82ee'), ('#f5deb3', '#f5deb3'), ('#ffffff', '#ffffff'), ('#f5f5f5', '#f5f5f5'), ('#ffff00', '#ffff00'), ('#9acd32', '#9acd32')], max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('Xlarge', 'Xlarge')], max_length=30),
        ),
    ]
