# Generated by Django 4.2.3 on 2023-07-25 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_media'),
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='delivery_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.delivery'),
        ),
    ]
