# Generated by Django 4.2.3 on 2023-07-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_image_alter_shopping_cart_delivery_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopping_cart',
            old_name='delivery_id',
            new_name='delivery',
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='delivery_method',
            field=models.CharField(choices=[('post', 'Post'), ('tipax', 'Tipax'), ('snapbar', 'Snapbar')], default='post', max_length=10),
        ),
    ]
