# Generated by Django 4.2.2 on 2023-07-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
