# Generated by Django 4.2.3 on 2023-08-12 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_like_dislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like_dislike',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='like_dislike',
            name='product_id',
        ),
        migrations.AddField(
            model_name='like_dislike',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comment'),
        ),
        migrations.AddField(
            model_name='like_dislike',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='like_dislike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users'),
        ),
    ]
