# Generated by Django 4.2.3 on 2023-08-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish_list',
            name='wishDate',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
