# Generated by Django 4.2.3 on 2023-07-30 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_color_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='core.order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('', '---'), ('white', 'white'), ('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('yellow', 'yellow'), ('purple', 'purple'), ('orange', 'orange'), ('pink', 'pink'), ('brown', 'brown'), ('gray', 'gray'), ('black', 'black')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('', '---'), ('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('Xlarge', 'Xlarge')], default=None, max_length=30, null=True),
        ),
    ]
