# Generated by Django 4.2.3 on 2023-07-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_sub_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sub_Category',
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
