# Generated by Django 4.2.3 on 2023-07-31 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cart_item_order_alter_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.users'),
            preserve_default=False,
        ),
    ]
