# Generated by Django 4.2.3 on 2023-07-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_shopping_cart_delivery_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_cart',
            name='total_amount_item',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='total_amount_product',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='total_price',
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='cart_items',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='send_price',
            field=models.IntegerField(default=0),
        ),
    ]
