# Generated by Django 4.2.3 on 2023-08-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_product_images_productimage_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FilePathField(path='image_productimage'),
        ),
    ]
