# Generated by Django 4.2.2 on 2023-07-10 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_item',
            old_name='users',
            new_name='user',
        ),
    ]
