# Generated by Django 4.2.3 on 2023-07-31 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items_user', to='core.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('', '---'), ('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('Xـlarge', 'Xـlarge')], default=None, max_length=30, null=True),
        ),
    ]
