# Generated by Django 4.2.2 on 2023-07-10 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_users_cart_item_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='shopping_cart',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shopping_cart'),
        ),
    ]
