# Generated by Django 4.2.3 on 2023-08-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_product_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
