# Generated by Django 4.2.2 on 2023-07-11 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='core.users'),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='shopping_cart',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_cartitem', to='core.shopping_cart'),
        ),
    ]
