# Generated by Django 4.2.3 on 2023-07-31 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_category_users_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish_list',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_wishlist', to='core.product'),
        ),
        migrations.AlterField(
            model_name='wish_list',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_wishlist', to='core.users'),
        ),
    ]
