# Generated by Django 4.2.3 on 2023-08-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_productimage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
    ]
