# Generated by Django 4.2.2 on 2023-07-16 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_total_amount_shopping_cart_total_amount_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='send_with_post',
            new_name='send_to_out_Capital',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='products_price',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='delivery',
            name='total_amount_product',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount_product',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='core.users'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='send_price',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
