# Generated by Django 4.2.3 on 2023-07-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='product_media'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
