# Generated by Django 4.2.3 on 2023-08-01 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_productimage_product_alter_product_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='name',
            new_name='send_with',
        ),
    ]
