# Generated by Django 4.2.3 on 2023-08-01 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_name_delivery_send_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='shopping_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoppingcart_cartitem', to='core.shopping_cart'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='shopping_cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoppingcart_delivery', to='core.shopping_cart'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_delivery', to='core.users'),
        ),
    ]
