# Generated by Django 4.2.3 on 2023-08-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cart_item_shopping_cart_delivery_shopping_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='total_amount_item',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='total_amount_product',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='cart_items',
            field=models.JSONField(default=list),
        ),
    ]
