# Generated by Django 4.2.2 on 2023-06-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_item', '0002_cart_item_create_cart_item_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
