# Generated by Django 4.2.2 on 2023-06-17 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_id'),
        ('shopping_cart', '0003_alter_shopping_cart_id'),
        ('product', '0004_product_sub_category_product_users_alter_product_id'),
        ('cart_item', '0003_alter_cart_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='product',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='cart_item',
            name='shopping_cart',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shopping_cart.shopping_cart'),
        ),
        migrations.AddField(
            model_name='cart_item',
            name='users',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
    ]
