# Generated by Django 4.2.2 on 2023-06-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_item', '0004_cart_item_product_cart_item_shopping_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
