# Generated by Django 4.2.2 on 2023-06-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_item', '0006_alter_cart_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
