# Generated by Django 4.2.2 on 2023-06-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name1',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
