# Generated by Django 4.2.2 on 2023-06-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_name1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name1',
        ),
        migrations.AddField(
            model_name='category',
            name='create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
