# Generated by Django 4.2.2 on 2023-06-17 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_id'),
        ('shopping_cart', '0003_alter_shopping_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='order',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
