# Generated by Django 4.2.2 on 2023-06-18 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
