# Generated by Django 4.2.2 on 2023-06-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_category', '0002_sub_category_create_sub_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
