# Generated by Django 4.2.2 on 2023-06-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_category', '0007_alter_sub_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
